builds:
  - goarch:
      - arm
      - amd64
    goarm:
      - 6
      - 7
release:
  github:
    owner: the-lightning-land
    name: sweetd
  draft: true
archive:
  wrap_in_directory: true
sign:
  artifacts: checksum
